#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

admin_pass=$(ynh_string_random --length=24)
admin_mail=$(ynh_user_get_info --username=$admin --key="mail")
admin_name=$(ynh_user_get_info --username=$admin --key="fullname")

# Store these values even if we don't need them, so they are printed in the post-install message
ynh_app_setting_set --key=admin_pass --value=$admin_pass
ynh_app_setting_set --key=admin_mail --value=$admin_mail

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Note-taking appliction" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL JOPLIN
#=================================================
ynh_script_progression "Building $app..."

pushd $install_dir/packages/server
	ynh_exec_warn_less corepack enable && corepack prepare yarn@latest --activate
	ynh_exec_warn_less ynh_exec_as_app COREPACK_ENABLE_DOWNLOAD_PROMPT=0 BUILD_SEQUENCIAL=1 yarn install --inline-builds
	ynh_exec_warn_less ynh_exec_as_app yarn build
	ynh_exec_warn_less ynh_exec_as_app yarn cache clean
	ynh_secure_remove .yarn/berry
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="App: Call this for testing"

#=================================================
# CHANGING DEFAULT ADMIN PASSWORD
#=================================================
ynh_script_progression "Changing default admin password..."

hashed_pwd=$(bcrypt_password "$admin_pass")

ynh_psql_db_shell <<< "
  UPDATE users
  SET password='$hashed_pwd', email='$admin_mail', full_name='$admin_name'
  WHERE email='admin@localhost'
"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
