#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

admin_pass=$(ynh_string_random --length=24)
admin_mail=$(ynh_user_get_info --username=$admin --key="mail")
admin_name=$(ynh_user_get_info --username=$admin --key="fullname")

# Store these values even if we don't need them, so they are printed in the post-install message
ynh_app_setting_set --app=$app --key=admin_pass --value=$admin_pass
ynh_app_setting_set --app=$app --key=admin_mail --value=$admin_mail

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=7

ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_setup_source --dest_dir="$install_dir"

chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

ynh_add_nginx_config

ynh_add_systemd_config

yunohost service add $app --description="Note-taking appliction" --log="/var/log/$app/$app.log"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template=".env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown $app:$app "$install_dir/.env"

#=================================================
# INSTALL JOPLIN
#=================================================
ynh_script_progression --message="Building $app..." --weight=10

pushd $install_dir/packages/server
 	ynh_use_nodejs
	ynh_exec_warn_less ynh_exec_as $app env $ynh_node_load_PATH BUILD_SEQUENCIAL=1 yarn install --inline-builds
	ynh_exec_warn_less ynh_exec_as $app env $ynh_node_load_PATH yarn build
	ynh_exec_warn_less ynh_exec_as $app env $ynh_node_load_PATH yarn cache clean
	ynh_secure_remove .yarn/berry
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="systemd" --line_match="App: Call this for testing"

#=================================================
# CHANGING DEFAULT ADMIN PASSWORD
#=================================================
ynh_script_progression --message="Changing default admin password..." --weight=1

hashed_pwd=$(bcrypt_password "$admin_pass")

ynh_psql_connect_as --user="$db_user" --password="$db_pwd" --database="$db_name" <<< "
  UPDATE users
  SET password='$hashed_pwd', email='$admin_mail', full_name='$admin_name'
  WHERE email='admin@localhost'
"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
