#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

if ynh_app_upgrading_from_version_before 3.2.11~ynh2; then
	# Purge old root directory's contents
	ynh_script_progression "Removing old files..."
	tmp=$(mktemp -d)
	mv -f $install_dir/* $install_dir/.[!.]* $tmp
	ynh_safe_rm "$tmp"
fi

ynh_safe_rm "$install_dir/packages"

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir/src"

chown -R $app:www-data "$install_dir/src"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# BUILD
#=================================================
ynh_script_progression "Building $app..."

mkdir $install_dir/build
mkdir $install_dir/build/.yarn
mkdir $install_dir/build/packages
chown -R $app:www-data "$install_dir/build"

mv $install_dir/src/.yarn/releases $install_dir/build/.yarn/releases
mv $install_dir/src/.yarn/patches $install_dir/build/.yarn/patches
mv $install_dir/src/package.json $install_dir/build
mv $install_dir/src/.yarnrc.yml $install_dir/build
mv $install_dir/src/yarn.lock $install_dir/build
mv $install_dir/src/gulpfile.js $install_dir/build
mv $install_dir/src/tsconfig.json $install_dir/build
mv $install_dir/src/packages/turndown $install_dir/build/packages/turndown
mv $install_dir/src/packages/turndown-plugin-gfm $install_dir/build/packages/turndown-plugin-gfm
mv $install_dir/src/packages/fork-htmlparser2 $install_dir/build/packages/fork-htmlparser2
mv $install_dir/src/packages/fork-sax $install_dir/build/packages/fork-sax
mv $install_dir/src/packages/fork-uslug $install_dir/build/packages/fork-uslug
mv $install_dir/src/packages/htmlpack $install_dir/build/packages/htmlpack
mv $install_dir/src/packages/renderer $install_dir/build/packages/renderer
mv $install_dir/src/packages/tools $install_dir/build/packages/tools
mv $install_dir/src/packages/utils $install_dir/build/packages/utils
mv $install_dir/src/packages/lib $install_dir/build/packages/lib
mv $install_dir/src/packages/server $install_dir/build/packages/server

ynh_replace --match="^.*onenote-converter.*$" --replace=" " --file="$install_dir/build/packages/lib/package.json"

ynh_safe_rm "$install_dir/src"

pushd $install_dir/build
	ynh_hide_warnings corepack enable && corepack prepare yarn@4.9.2 --activate
	ynh_hide_warnings ynh_exec_as_app COREPACK_ENABLE_DOWNLOAD_PROMPT=0  BUILD_SEQUENCIAL=1 yarn install --inline-builds
	ynh_hide_warnings ynh_exec_as_app yarn cache clean
	ynh_safe_rm "$install_dir/build/.yarn/berry"
popd

mv $install_dir/build/packages $install_dir
ynh_safe_rm "$install_dir/build"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Note-taking appliction" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="App: Call this for testing"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
